### ISSUE TITLE
"npm install" command buildi patlatiyor

### ISSUE THREAD

**Issue by borakrc** [ugurdonmez/kinder-mobile#9]
bu translate isine bakarken ng-translate modulunu package.json'a ekleyip npm install yaptim. build patladi. hatayi bulmak icin dependency versionlarini gozden geciriyorum. sonra translate isine devam edicem.

```
Runtime Error
ctorParameters.map is not a function
Stack
TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:8100/build/main.js:45937:45)
    at Reflector.parameters (http://localhost:8100/build/main.js:46071:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:8100/build/main.js:26078:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:8100/build/main.js:26043:26)
    at http://localhost:8100/build/main.js:26186:41
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:8100/build/main.js:26166:19)
    at http://localhost:8100/build/main.js:25864:71
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/main.js:25855:44)
Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.48
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 6.9.3
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```

**Comment by ugurdonmez** [comment]
package.json a elle ekleme yapmana gerek yok. npm install da --save gibi
bir seyler vardi. otomatik update ediyor. git reset yapip oyle
deneyebilirsin.

**Comment by borakrc** [comment]
baska bi sikinti var. angularfire2'ye update gelmis, onun istedigi rxjs surumunu de yukseltmisler. ama onun rxjs surumuyle angular kutuphanelerinin istedigi rxjs surumu cakisiyor. halledince versiyonu sabitleyip commitleyecegim package.json'i. git reset deyip npm install desem de hata aliyorum su anda.

**Comment by borakrc** [comment]
evet, angularfire2'nin yeni surumu rxjs@^5.0.1 istiyor en az, ama bizim angular kutuphaneleri sadece 5.0.0-beta.12 ile calisiyor. hallettim galiba, pushluyorum.
